kind: pipeline
type: docker
name: scaladoc-x

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier/cache
      - /drone/.sbt

- name: build
  image: eed3si9n/sbt:jdk11-alpine
  when:
    branch: master
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - git log | head -n 20
  - sbt +clean +coverage +test +coverageReport
  - curl -s https://codecov.io/bash | bash -s -- -X gcov -X coveragepy -X xcode -X gcovout

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier/cache
      - /drone/.sbt
