dist: trusty

sudo: false

language: scala

scala:
   - 2.13.1

jdk: openjdk11

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)